#!/bin/bash

HYPR_PATH=~/.config/hypr
WAYBAR_PATH=~/.config/waybar
WOFI_PATH=~/.config/wofi

# Check which waybar theme is set
THEMEIS=$(readlink -f $WAYBAR_PATH/style.css | xargs basename | cut -d '-' -f2)
# Check which waybar config is set
CONFIGIS=$(readlink -f $WAYBAR_PATH/config.jsonc | xargs basename | cut -d '-' -f2)

#if the theme is not htb then we need to switch to it
if [[ $THEMEIS != "htb.css" ]]; then
    SWITCHTO="-htb"
	hyprctl notify 6 2500 "rgb(9fef00)" "fontsize:28 Cambiando a tema HTB..."
	#set kitty theme
	kitty +kitten themes --reload-in=all Molokai
else
	hyprctl notify 6 2500 "rgb(0d6efd)" "fontsize:28 Volviendo al tema default..."
	#set kitty theme
	kitty +kitten themes --reload-in=all Github Dark
fi

#set the waybar theme
ln -sf $WAYBAR_PATH/styles/style${SWITCHTO:-"-default"}.css $WAYBAR_PATH/style.css

# podria switchear la configuracion tambien, una base, una para estudio/trabajo, o varias sin mas
ln -sf $WAYBAR_PATH/configs/config${SWITCHTO:-"-default"}.jsonc $WAYBAR_PATH/config.jsonc

#set the wofi theme
# ln -sf ~/.config/wofi/styles/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme (leave Dracula theme for all)
# xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
# xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

#set the GTK theme (leave Dracula theme for all)
# gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
# gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"

SWITCHTO=$([[ -n $SWITCHTO ]] && echo "htb")
#change the background image and be cool about it ;)
# swww img ~/.config/hypr/wallpapers/${SWITCHTO:-"00-default"}.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
swww img ~/.config/hypr/wallpapers/${SWITCHTO:-"00-default"}.jpg --transition-fps 60 --transition-type grow --transition-duration 2 --transition-pos 25,25 --invert-y

#restart the waybar
killall -SIGUSR2 waybar
